# https://github.com/toml-lang/toml

[Core]
    strategy = "arbritage-simple-0v.1.0"

[Exchanges]
  [Exchange.binance]
  name = "test_1"
  uri = "test_1_uri"

  [Exchange.DYDX]
  name = "test_2"
  uri = "test_2_uri"
